# -*- coding: utf-8 -*-
"""Tarea6_fraude_tarjetas_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtkO9RYCZt_9Juuxnj3mFFayZDFJWunI

# Detección de fraude en tarjetas de crédito con una Red Neuronal
**Tarea de Redes Neuronales Artificiales — Dr. Jorge Velazquez-Castro**

Dataset: [Credit Card Fraud Detection (mlg-ulb)](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud)

Este cuaderno entrena **varios modelos** y muestra las curvas de **loss** y **accuracy** (entrenamiento y validación), registrando todo en **MLflow**.

**Cómo ejecutarlo:** `Entorno de ejecución > Ejecutar todo`. Cuando se te pida, sube el archivo `creditcard.csv`.
"""

!pip install -q mlflow

import numpy as np, pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, average_precision_score
import mlflow

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Tarea6_DGC/creditcard.csv")
print(f'Dim: {df.shape}')
df.head()

SEED = 42
np.random.seed(SEED); tf.random.set_seed(SEED)
mlflow.set_experiment('fraude_tarjetas_rnn')

fraude = int(df['Class'].sum())
print('Filas:', len(df), '| Fraudes:', fraude, '(', round(100*fraude/len(df), 3), '%)')

# 'V1'..'V28' provienen de un PCA (ya escaladas). Escalamos 'Amount' y 'Time'.
scaler = RobustScaler()
df[['Amount','Time']] = scaler.fit_transform(df[['Amount','Time']])
X = df.drop(columns=['Class']).values.astype('float32')
y = df['Class'].values.astype('int32')

# 60% train / 20% val / 20% test (estratificado)
X_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=0.40, stratify=y, random_state=SEED)
X_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=0.50, stratify=y_tmp, random_state=SEED)
print('train', len(y_train), '| val', len(y_val), '| test', len(y_test))

# 4) Modelo (MLP) y utilidades para el desbalance y las gráficas
def build_model(input_dim, hidden=(32,16), dropout=0.0, lr=1e-3):
    m = keras.Sequential(name='mlp_fraude')
    m.add(keras.Input(shape=(input_dim,)))
    for i, u in enumerate(hidden):
        m.add(layers.Dense(u, activation='relu', name=f'densa_{i+1}'))
        if dropout > 0:
            m.add(layers.Dropout(dropout, name=f'dropout_{i+1}'))
    m.add(layers.Dense(1, activation='sigmoid', name='salida'))
    m.compile(optimizer=keras.optimizers.Adam(lr),
              loss='binary_crossentropy',
              metrics=['accuracy', keras.metrics.AUC(name='auc'),
                       keras.metrics.Precision(name='precision'),
                       keras.metrics.Recall(name='recall')])
    return m

def class_weights(y):
    neg, pos = np.bincount(y)
    total = neg + pos
    return {0: total/(2.0*neg), 1: total/(2.0*pos)}

def undersample(X, y, ratio=1.0, seed=SEED):
    rng = np.random.default_rng(seed)
    pos = np.where(y==1)[0]; neg = np.where(y==0)[0]
    neg = rng.choice(neg, size=min(len(neg), int(len(pos)*ratio)), replace=False)
    keep = np.concatenate([pos, neg]); rng.shuffle(keep)
    return X[keep], y[keep]

def plot_history(h, name):
    e = range(1, len(h.history['loss'])+1)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4.5))
    a1.plot(e, h.history['loss'], 'o-', label='Entrenamiento')
    a1.plot(e, h.history['val_loss'], 's-', label='Validación')
    a1.set_title('Loss — '+name); a1.set_xlabel('Época'); a1.set_ylabel('Loss'); a1.legend(); a1.grid(alpha=0.3)
    a2.plot(e, h.history['accuracy'], 'o-', label='Entrenamiento')
    a2.plot(e, h.history['val_accuracy'], 's-', label='Validación')
    a2.set_title('Accuracy — '+name); a2.set_xlabel('Época'); a2.set_ylabel('Accuracy'); a2.legend(); a2.grid(alpha=0.3)
    fig.tight_layout()
    os.makedirs('results', exist_ok=True)
    fig.savefig('results/curvas_'+name+'.png', dpi=120)
    plt.show()

# Commented out IPython magic to ensure Python compatibility.
# 5) VARIOS entrenamientos + gráficas de loss/accuracy (train y val). MLflow es opcional.
import os
from contextlib import nullcontext
os.makedirs('results', exist_ok=True)

EXPERIMENTS = [
    dict(name='baseline',         desc='MLP simple, sin tratar el desbalance', hidden=(32,16), dropout=0.0),
    dict(name='pesos_clase',      desc='MLP + pesos de clase',                 hidden=(32,16), dropout=0.0, class_weight=True),
    dict(name='profundo_dropout', desc='Red más profunda + dropout + pesos',   hidden=(64,32,16), dropout=0.3, class_weight=True),
    dict(name='submuestreo',      desc='Datos balanceados por submuestreo',    hidden=(32,16), dropout=0.2, undersample=True),
]
EPOCHS, BATCH = 40, 2048
resumen = []

def mlrun(name):
    try:
        return mlflow.start_run(run_name=name)
    except Exception as e:
        print('  (MLflow desactivado:', e, ')'); return nullcontext()

for cfg in EXPERIMENTS:
    print('\n====', cfg['name'], '—', cfg['desc'], '====')
    keras.backend.clear_session(); np.random.seed(SEED); tf.random.set_seed(SEED)
    Xtr, ytr, cw = X_train, y_train, None
    if cfg.get('undersample'):
        Xtr, ytr = undersample(X_train, y_train); print('  train balanceado:', len(ytr))
    if cfg.get('class_weight'):
        cw = class_weights(y_train); print('  pesos de clase:', cw)
    model = build_model(X_train.shape[1], cfg.get('hidden',(32,16)), cfg.get('dropout',0.0))

    with mlrun(cfg['name']):
        try:
            mlflow.log_params(dict(hidden=str(cfg.get('hidden')), dropout=cfg.get('dropout',0.0),
                                   epochs=EPOCHS, batch=BATCH,
                                   class_weight=bool(cfg.get('class_weight')),
                                   undersample=bool(cfg.get('undersample'))))
        except Exception: pass

        hist = model.fit(Xtr, ytr, validation_data=(X_val, y_val),
                         epochs=EPOCHS, batch_size=BATCH, class_weight=cw, verbose=2)

        try:
            for metric, vals in hist.history.items():
                for step, v in enumerate(vals):
                    mlflow.log_metric(metric, float(v), step=step)
        except Exception as e:
            print('  (no se pudieron loguear métricas:', e, ')')

        try:
            plot_history(hist, cfg['name'])
            try: mlflow.log_artifact('results/curvas_'+cfg['name']+'.png', artifact_path='curvas')
            except Exception: pass
        except Exception as e:
            print('  (no se pudo graficar:', e, ')')

        # Evaluación en TEST (esto SIEMPRE se ejecuta y llena 'resumen')
        proba = model.predict(X_test, batch_size=4096, verbose=0).ravel()
        pred = (proba >= 0.5).astype(int)
        rep = classification_report(y_test, pred, target_names=['normal','fraude'],
                                    output_dict=True, zero_division=0)
        roc = roc_auc_score(y_test, proba); pr = average_precision_score(y_test, proba)
        m = dict(name=cfg['name'], roc_auc=roc, pr_auc=pr,
                 precision_fraude=rep['fraude']['precision'],
                 recall_fraude=rep['fraude']['recall'],
                 f1_fraude=rep['fraude']['f1-score'])
        try: mlflow.log_metrics({k: float(v) for k, v in m.items() if k != 'name'})
        except Exception: pass
        print('  matriz de confusión (test):\n', confusion_matrix(y_test, pred))
        print('  ROC-AUC %.4f | PR-AUC %.4f | recall %.4f | precision %.4f'
#               % (roc, pr, m['recall_fraude'], m['precision_fraude']))
        resumen.append(m)

print('\n✅ Entrenamientos completados:', len(resumen))

# 6) Resumen comparativo de los entrenamientos
res = pd.DataFrame(resumen).set_index('name').round(4)
res.to_csv('results/resumen.csv')
print(res.to_string())

ax = res[['roc_auc','pr_auc','recall_fraude','precision_fraude']].plot.bar(figsize=(10, 4.5), rot=0)
ax.set_title('Comparación de modelos (conjunto de test)'); ax.set_ylabel('Métrica'); ax.legend(loc='lower right')
plt.tight_layout(); plt.savefig('results/comparacion.png', dpi=120); plt.show()

!zip -r resultados.zip results mlruns
from google.colab import files; files.download('resultados.zip')